// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
    name,
    code,
    department_id
) VALUES (
    $1, $2, $3
)
RETURNING id, name, code, department_id, created_at, updated_at
`

type CreateBranchParams struct {
	Name         string    `json:"name"`
	Code         string    `json:"code"`
	DepartmentID uuid.UUID `json:"department_id"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.Name, arg.Code, arg.DepartmentID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchByCode = `-- name: GetBranchByCode :one
SELECT id, name, code, department_id, created_at, updated_at FROM branches
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetBranchByCode(ctx context.Context, code string) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByCode, code)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
