// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: department.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    name,
    hod_name,
    dhod_name
) VALUES (
$1, $2,$3
)
RETURNING id, name, hod_name, hod_id, dhod_name, dhod_id, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name     string      `json:"name"`
	HodName  pgtype.Text `json:"hod_name"`
	DhodName pgtype.Text `json:"dhod_name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.HodName, arg.DhodName)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HodName,
		&i.HodID,
		&i.DhodName,
		&i.DhodID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByName = `-- name: GetDepartmentByName :one
SELECT id, name, hod_name, hod_id, dhod_name, dhod_id, created_at, updated_at FROM departments
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetDepartmentByName(ctx context.Context, name string) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByName, name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HodName,
		&i.HodID,
		&i.DhodName,
		&i.DhodID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
