// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Userrole string

const (
	UserroleStudent Userrole = "student"
	UserroleTeacher Userrole = "teacher"
	UserroleHod     Userrole = "hod"
	UserroleDhod    Userrole = "dhod"
	UserroleAdmin   Userrole = "admin"
	UserroleCrew    Userrole = "crew"
)

func (e *Userrole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Userrole(s)
	case string:
		*e = Userrole(s)
	default:
		return fmt.Errorf("unsupported scan type for Userrole: %T", src)
	}
	return nil
}

type NullUserrole struct {
	Userrole Userrole `json:"userrole"`
	Valid    bool     `json:"valid"` // Valid is true if Userrole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserrole) Scan(value interface{}) error {
	if value == nil {
		ns.Userrole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Userrole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserrole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Userrole), nil
}

type Branch struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Code         string    `json:"code"`
	DepartmentID uuid.UUID `json:"department_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Department struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	HodName   pgtype.Text `json:"hod_name"`
	HodID     pgtype.UUID `json:"hod_id"`
	DhodName  pgtype.Text `json:"dhod_name"`
	DhodID    pgtype.UUID `json:"dhod_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Semester struct {
	ID        uuid.UUID `json:"id"`
	Number    int32     `json:"number"`
	Name      string    `json:"name"`
	BranchID  uuid.UUID `json:"branch_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Student struct {
	ID                uuid.UUID   `json:"id"`
	RollNo            string      `json:"roll_no"`
	FirstName         string      `json:"first_name"`
	MiddleName        pgtype.Text `json:"middle_name"`
	LastName          string      `json:"last_name"`
	Image             pgtype.Text `json:"image"`
	Batch             pgtype.Text `json:"batch"`
	UserID            uuid.UUID   `json:"user_id"`
	BranchID          uuid.UUID   `json:"branch_id"`
	CurrentSemesterID pgtype.UUID `json:"current_semester_id"`
	RfidTagID         pgtype.Text `json:"rfid_tag_id"`
	FingerprintHash   pgtype.Text `json:"fingerprint_hash"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type Subject struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Code       string      `json:"code"`
	IsLab      bool        `json:"is_lab"`
	Credits    pgtype.Int4 `json:"credits"`
	BranchID   uuid.UUID   `json:"branch_id"`
	SemesterID uuid.UUID   `json:"semester_id"`
	TeacherID  uuid.UUID   `json:"teacher_id"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type Teacher struct {
	ID              uuid.UUID   `json:"id"`
	CardNo          string      `json:"card_no"`
	FirstName       string      `json:"first_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	LastName        string      `json:"last_name"`
	Image           pgtype.Text `json:"image"`
	UserID          uuid.UUID   `json:"user_id"`
	DepartmentID    uuid.UUID   `json:"department_id"`
	RfidTagID       pgtype.Text `json:"rfid_tag_id"`
	FingerprintHash pgtype.Text `json:"fingerprint_hash"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	IsActive           bool               `json:"is_active"`
	IsEmailVerified    bool               `json:"is_email_verified"`
	IsProfileCompleted bool               `json:"is_profile_completed"`
	UserRole           Userrole           `json:"user_role"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}
