// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBranchByCode(ctx context.Context, code string) (Branch, error)
	GetDepartmentByName(ctx context.Context, name string) (Department, error)
}

var _ Querier = (*Queries)(nil)
