// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: semester.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSemester = `-- name: CreateSemester :one
INSERT INTO semesters(
    number,
    name,
    branch_id
)VALUES(
    $1,$2,$3
)
RETURNING id, number, name, branch_id, created_at, updated_at
`

type CreateSemesterParams struct {
	Number   int32     `json:"number"`
	Name     string    `json:"name"`
	BranchID uuid.UUID `json:"branch_id"`
}

func (q *Queries) CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, createSemester, arg.Number, arg.Name, arg.BranchID)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
