// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students(
    roll_no,
    first_name,
    middle_name ,
    last_name,
    image ,
    batch,
    user_id ,
    branch_id ,
    current_semester_id
) VALUES (
$1,$2,$3,$4,$5,$6,$7,$8,$9
)
RETURNING id, roll_no, first_name, middle_name, last_name, image, batch, user_id, branch_id, current_semester_id, rfid_tag_id, fingerprint_hash, created_at, updated_at, deleted_at
`

type CreateStudentParams struct {
	RollNo            string      `json:"roll_no"`
	FirstName         string      `json:"first_name"`
	MiddleName        pgtype.Text `json:"middle_name"`
	LastName          string      `json:"last_name"`
	Image             pgtype.Text `json:"image"`
	Batch             pgtype.Text `json:"batch"`
	UserID            uuid.UUID   `json:"user_id"`
	BranchID          uuid.UUID   `json:"branch_id"`
	CurrentSemesterID pgtype.UUID `json:"current_semester_id"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.RollNo,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Image,
		arg.Batch,
		arg.UserID,
		arg.BranchID,
		arg.CurrentSemesterID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.RollNo,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Image,
		&i.Batch,
		&i.UserID,
		&i.BranchID,
		&i.CurrentSemesterID,
		&i.RfidTagID,
		&i.FingerprintHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStudentByRollNo = `-- name: GetStudentByRollNo :one
SELECT id, roll_no, first_name, middle_name, last_name, image, batch, user_id, branch_id, current_semester_id, rfid_tag_id, fingerprint_hash, created_at, updated_at, deleted_at FROM students
WHERE roll_no = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetStudentByRollNo(ctx context.Context, rollNo string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByRollNo, rollNo)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.RollNo,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Image,
		&i.Batch,
		&i.UserID,
		&i.BranchID,
		&i.CurrentSemesterID,
		&i.RfidTagID,
		&i.FingerprintHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
