// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teacher.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teachers(
    card_no,
    first_name,
    middle_name ,
    last_name,
    image ,
    user_id ,
    department_id 
) VALUES (
$1,$2,$3,$4,$5,$6,$7
)
RETURNING id, card_no, first_name, middle_name, last_name, image, user_id, department_id, rfid_tag_id, fingerprint_hash, created_at, updated_at
`

type CreateTeacherParams struct {
	CardNo       string      `json:"card_no"`
	FirstName    string      `json:"first_name"`
	MiddleName   pgtype.Text `json:"middle_name"`
	LastName     string      `json:"last_name"`
	Image        pgtype.Text `json:"image"`
	UserID       uuid.UUID   `json:"user_id"`
	DepartmentID uuid.UUID   `json:"department_id"`
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, createTeacher,
		arg.CardNo,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Image,
		arg.UserID,
		arg.DepartmentID,
	)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.CardNo,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Image,
		&i.UserID,
		&i.DepartmentID,
		&i.RfidTagID,
		&i.FingerprintHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherByCardNo = `-- name: GetTeacherByCardNo :one
SELECT id, card_no, first_name, middle_name, last_name, image, user_id, department_id, rfid_tag_id, fingerprint_hash, created_at, updated_at FROM teachers
WHERE card_no = $1
LIMIT 1
`

func (q *Queries) GetTeacherByCardNo(ctx context.Context, cardNo string) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacherByCardNo, cardNo)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.CardNo,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Image,
		&i.UserID,
		&i.DepartmentID,
		&i.RfidTagID,
		&i.FingerprintHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
