// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teacher_v2.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTeacherByUserID = `-- name: GetTeacherByUserID :one
SELECT id, card_no, first_name, middle_name, last_name, image, user_id, department_id, rfid_tag_id, fingerprint_hash, created_at, updated_at, deleted_at FROM teachers
WHERE user_id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTeacherByUserID(ctx context.Context, userID uuid.UUID) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacherByUserID, userID)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.CardNo,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Image,
		&i.UserID,
		&i.DepartmentID,
		&i.RfidTagID,
		&i.FingerprintHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTeachersByDepartment = `-- name: ListTeachersByDepartment :many
SELECT id, card_no, first_name, middle_name, last_name, image, user_id, department_id, rfid_tag_id, fingerprint_hash, created_at, updated_at, deleted_at FROM teachers
WHERE department_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListTeachersByDepartment(ctx context.Context, departmentID uuid.UUID) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listTeachersByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.ID,
			&i.CardNo,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.Image,
			&i.UserID,
			&i.DepartmentID,
			&i.RfidTagID,
			&i.FingerprintHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeacherDepartment = `-- name: UpdateTeacherDepartment :one
UPDATE teachers
SET department_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, card_no, first_name, middle_name, last_name, image, user_id, department_id, rfid_tag_id, fingerprint_hash, created_at, updated_at, deleted_at
`

type UpdateTeacherDepartmentParams struct {
	ID           uuid.UUID `json:"id"`
	DepartmentID uuid.UUID `json:"department_id"`
}

func (q *Queries) UpdateTeacherDepartment(ctx context.Context, arg UpdateTeacherDepartmentParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, updateTeacherDepartment, arg.ID, arg.DepartmentID)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.CardNo,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Image,
		&i.UserID,
		&i.DepartmentID,
		&i.RfidTagID,
		&i.FingerprintHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
