// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  user_role
) VALUES (
  $1, $2,$3 
)
RETURNING id, email, password_hash, is_active, is_email_verified, is_profile_completed, user_role, last_login_at, password_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	UserRole     Userrole `json:"user_role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.UserRole)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.IsProfileCompleted,
		&i.UserRole,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
