// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  user_role
) VALUES (
  $1, $2,$3 
)
RETURNING id, email, password_hash, is_active, is_email_verified, is_profile_completed, user_role, last_login_at, password_changed_at, created_at, updated_at, deleted_at, department_id
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	UserRole     Userrole `json:"user_role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.UserRole)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.IsProfileCompleted,
		&i.UserRole,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DepartmentID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_active, is_email_verified, is_profile_completed, user_role, last_login_at, password_changed_at, created_at, updated_at, deleted_at, department_id FROM users
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.IsProfileCompleted,
		&i.UserRole,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DepartmentID,
	)
	return i, err
}

const updateUserProfileCompleted = `-- name: UpdateUserProfileCompleted :one
UPDATE users
SET is_profile_completed = $2
WHERE id = $1
RETURNING id, email, password_hash, is_active, is_email_verified, is_profile_completed, user_role, last_login_at, password_changed_at, created_at, updated_at, deleted_at, department_id
`

type UpdateUserProfileCompletedParams struct {
	ID                 uuid.UUID `json:"id"`
	IsProfileCompleted bool      `json:"is_profile_completed"`
}

func (q *Queries) UpdateUserProfileCompleted(ctx context.Context, arg UpdateUserProfileCompletedParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfileCompleted, arg.ID, arg.IsProfileCompleted)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.IsProfileCompleted,
		&i.UserRole,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DepartmentID,
	)
	return i, err
}
